const images: any = {
    arrow: require('./arrow.svg'),
    belize: require('./belize.svg'),
    branches: require('./branches.jpg'),
    chichenItza: require('./chichen-itza.jpg'),
    chichenItzaLarge: require('./chichen-itza-large.jpg'),
    chichenItzaZoom: require('./chichen-itza-zoom.jpg'),
    controls: require('./controls.svg'),
    decor: require('./decor.jpg'),
    dots: require('./dot.svg'),
    facebook: require('./facebook.svg'),
    foret: require('./foret.jpg'),
    foretCanyon: require('./foret-canyon.jpg'),
    guatemala: require('./guatemala.svg'),
    instagram: require('./instagram.svg'),
    loader: require('./loader.svg'),
    logo: require('./logo.jpg'),
    mapMenu: require('./map-menu.svg'),
    mer: require('./mer.jpg'),
    mexico: require('./mexico.svg'),
    mexique: require('./mexique.jpg'),
    paysage: require('./paysage.jpg'),
    plane: require('./plane.jpg'),
    portraitStatue: require('./portrait-statue.jpg'),
    quote: require('./quote.svg'),
    sound: require('./sound.svg'),
    statue: require('./statue.jpg')
}
export default images;